package dev.geanbrandao.minhasdespesas.ui.theme

import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF006c52)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF82f8d0)
val md_theme_light_onPrimaryContainer = Color(0xFF002117)
val md_theme_light_secondary = Color(0xFF4b6359)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFcee9dc)
val md_theme_light_onSecondaryContainer = Color(0xFF082018)
val md_theme_light_tertiary = Color(0xFF3f6375)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFc3e8fe)
val md_theme_light_onTertiaryContainer = Color(0xFF001e2b)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfafdf9)
val md_theme_light_onBackground = Color(0xFF191c1b)
val md_theme_light_surface = Color(0xFFfafdf9)
val md_theme_light_onSurface = Color(0xFF191c1b)
val md_theme_light_surfaceVariant = Color(0xFFdbe5df)
val md_theme_light_onSurfaceVariant = Color(0xFF3f4944)
val md_theme_light_outline = Color(0xFF707974)
val md_theme_light_inverseOnSurface = Color(0xFFeff2ee)
val md_theme_light_inverseSurface = Color(0xFF2e312f)

val md_theme_dark_primary = Color(0xFF64dbb4)
val md_theme_dark_onPrimary = Color(0xFF003829)
val md_theme_dark_primaryContainer = Color(0xFF00513c)
val md_theme_dark_onPrimaryContainer = Color(0xFF82f8d0)
val md_theme_dark_secondary = Color(0xFFb2ccc0)
val md_theme_dark_onSecondary = Color(0xFF1e352c)
val md_theme_dark_secondaryContainer = Color(0xFF344b42)
val md_theme_dark_onSecondaryContainer = Color(0xFFcee9dc)
val md_theme_dark_tertiary = Color(0xFFa7cce1)
val md_theme_dark_onTertiary = Color(0xFF0b3445)
val md_theme_dark_tertiaryContainer = Color(0xFF264b5d)
val md_theme_dark_onTertiaryContainer = Color(0xFFc3e8fe)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1b)
val md_theme_dark_onBackground = Color(0xFFe1e3e0)
val md_theme_dark_surface = Color(0xFF191c1b)
val md_theme_dark_onSurface = Color(0xFFe1e3e0)
val md_theme_dark_surfaceVariant = Color(0xFF3f4944)
val md_theme_dark_onSurfaceVariant = Color(0xFFbfc9c3)
val md_theme_dark_outline = Color(0xFF8a938e)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1b)
val md_theme_dark_inverseSurface = Color(0xFFe1e3e0)

val seed = Color(0xFF51a488)
val error = Color(0xFFba1b1b)